name: 'tests'

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  run-tests:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      - name: '`go build`'
        run: |
          go build ./...

      - name: '`go vet`'
        run: |
          go vet ./...

      - name: 'Run tests.'
        run: |
          go test -v ./...
